server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.186.136:3306/cloud_user?useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    # 是否需要进行服务注册
    register-with-eureka: true
    # 是否需要进行服务拉取
    fetch-registry: true